name: my_blog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  image_picker: ^1.1.2
  # Removed cached_network_image since we're using local assets now.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Ensure the asset folder is correctly linked
  assets:
    - assets/images/ # Note: Ensure you have an images folder under assets.

# Add fonts section if needed in the future.
# For more details regarding fonts and assets, refer to the official documentation.
